const cards = [
  {
    id: 0,
    artist: "J Dilla",
    media: "/beer1.avif",
    track: "Track 1",
    date: "2022-10-15",
    copy: "Lorem ipsum dolor sit amet.",
    tags: ["Hip-Hop", "Beats"],
  },
  {
    id: 1,
    artist: "Jay Z",
    media: "/beer2.avif",
    track: "Track 2",
    date: "2022-10-14",
    copy: "Consectetur adipiscing elit.",
    tags: ["Hip-Hop", "Rap"],
  },
  {
    id: 2,
    artist: "Nas",
    media: "/beer3.avif",
    track: "Track 3",
    date: "2022-10-13",
    copy: "Sed do eiusmod tempor incididunt.",
    tags: ["Hip-Hop", "Rap"],
  },
  {
    id: 3,
    artist: "Lords of the Underground",
    media: "/beer1.avif",
    track: "Track 4",
    date: "2022-10-12",
    copy: "Ut labore et dolore magna aliqua.",
    tags: ["Hip-Hop", "Old School"],
  },
  {
    id: 4,
    artist: "Public Enemy",
    media: "/beer2.avif",
    track: "Track 5",
    date: "2022-10-11",
    copy: "Ut enim ad minim veniam.",
    tags: ["Hip-Hop", "Rap"],
  },
  {
    id: 5,
    artist: "Kendrick Lamar",
    media: "/beer3.avif",
    track: "Track 6",
    date: "2022-10-10",
    copy: "Quis nostrud exercitation ullamco.",
    tags: ["Hip-Hop", "Rap"],
  },
  {
    id: 6,
    artist: "Big L",
    media: "/beer1.avif",
    track: "Track 7",
    date: "2022-10-09",
    copy: "Duis aute irure dolor in reprehenderit.",
    tags: ["Hip-Hop", "Rap"],
  },
  {
    id: 7,
    artist: "Biggie",
    media: "/beer2.avif",
    track: "Track 8",
    date: "2022-10-08",
    copy: "Excepteur sint occaecat cupidatat non proident.",
    tags: ["Hip-Hop", "Rap"],
  },
  {
    id: 8,
    artist: "Tupac",
    media: "/beer3.avif",
    track: "Track 9",
    date: "2022-10-07",
    copy: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
    tags: ["Hip-Hop", "Rap"],
  },
  {
    id: 9,
    artist: "Eminem",
    media: "/beer1.avif",
    track: "Track 10",
    date: "2022-10-06",
    copy: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    tags: ["Hip-Hop", "Rap"],
  },
];

export default cards;
