const randomColorGenerator = () => {
  const randomColor = `rgb(${Math.floor(Math.random() * 256)} ${Math.floor(Math.random() * 256)} ${Math.floor(Math.random() * 256)})`;
  return randomColor;
};

const cards = [
  {
    id: 0,
    artist: "J Dilla",
    media: "/beer1.avif",
    track: "Track Name",
    date: "2024-02-10",
    copy: "Lorem ipsum dolor sit amet.",
    tags: ["Hip-Hop", "Beats"],
    background: randomColorGenerator(),
  },
  {
    id: 1,
    artist: "Jay Z",
    media: "/beer2.avif",
    track: "Track Name",
    date: "2024-02-01",
    copy: "Consectetur adipiscing elit.",
    tags: ["Hip-Hop", "Rap"],
    background: randomColorGenerator(),
  },
  {
    id: 2,
    artist: "Nas",
    media: "/beer3.avif",
    track: "Track Name",
    date: "2024-01-24",
    copy: "Sed do eiusmod tempor incididunt.",
    tags: ["Hip-Hop", "Rap"],
    background: randomColorGenerator(),
  },
  {
    id: 3,
    artist: "Lords of the Underground",
    media: "/beer1.avif",
    track: "Track Name",
    date: "2024-01-12",
    copy: "Ut labore et dolore magna aliqua.",
    tags: ["Hip-Hop", "Old School"],
    background: randomColorGenerator(),
  },
  {
    id: 4,
    artist: "Public Enemy",
    media: "/beer2.avif",
    track: "Track Name",
    date: "2023-12-11",
    copy: "Ut enim ad minim veniam.",
    tags: ["Hip-Hop", "Rap"],
    background: randomColorGenerator(),
  },
  {
    id: 5,
    artist: "Kendrick Lamar",
    media: "/beer3.avif",
    track: "Track Name",
    date: "2023-12-10",
    copy: "Quis nostrud exercitation ullamco.",
    tags: ["Hip-Hop", "Rap"],
    background: randomColorGenerator(),
  },
  {
    id: 6,
    artist: "Big L",
    media: "/beer1.avif",
    track: "Track Name",
    date: "2023-11-09",
    copy: "Duis aute irure dolor in reprehenderit.",
    tags: ["Hip-Hop", "Rap"],
    background: randomColorGenerator(),
  },
  {
    id: 7,
    artist: "Biggie",
    media: "/beer2.avif",
    track: "Track Name",
    date: "2023-10-08",
    copy: "Excepteur sint occaecat cupidatat non proident.",
    tags: ["Hip-Hop", "Rap"],
    background: randomColorGenerator(),
  },
  {
    id: 8,
    artist: "Tupac",
    media: "/beer3.avif",
    track: "Track Name",
    date: "2023-10-07",
    copy: "Sunt in culpa qui officia deserunt mollit anim id est laborum.",
    tags: ["Hip-Hop", "Rap"],
    background: randomColorGenerator(),
  },
  {
    id: 9,
    artist: "Eminem",
    media: "/beer1.avif",
    track: "Track Name0",
    date: "2023-10-06",
    copy: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    tags: ["Hip-Hop", "Rap"],
    background: randomColorGenerator(),
  },
];

export default cards;
